server:
  port: 8080

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-bff
          uri: lb://user-bff
          predicates:
            - Path=/api/**,/ws/**,/graphql

